# ***************** Universidad de los Andes ***********************
# ****** Departamento de Ingeniería de Sistemas y Computación ******
# ********** Arquitectura y diseño de Software - ISIS2503 **********
#
# Infraestructura para laboratorio de Autenticación
# Elementos a desplegar:
# 1. Firewalls:
#    - authd-firewall-django
#    - authd-firewall-db
# 2. Instancias MVs:
#    - authd-django-instance (repositorio clonado y requerimientos instalados)
#    - authd-db-instance (postgreSQL instalado y configurado)

resources:
# Firewall rules
- name: authd-firewall-django
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges: 
    - 0.0.0.0/0
    targetTags:
    - authd-django
    allowed:
    - IPProtocol: TCP
      ports: 
      - 8080
- name: authd-firewall-db
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceTags: 
    - authd-django
    targetTags:
    - authd-db
    allowed:
    - IPProtocol: TCP
      ports: 
      - 5432

# Database instance
- type: compute.v1.instance
  name: authd-db-instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
      networkIP: 10.128.0.60
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - authd-db
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo -u postgres psql -c "CREATE USER monitoring_user WITH PASSWORD 'isis2503';"
          sudo -u postgres createdb -O monitoring_user monitoring_db
          echo "host all all 0.0.0.0/0 trust" | sudo tee -a /etc/postgresql/12/main/pg_hba.conf
          echo "listen_addresses='*'" | sudo tee -a /etc/postgresql/12/main/postgresql.conf
          echo "max_connections=2000" | sudo tee -a /etc/postgresql/12/main/postgresql.conf
          sudo service postgresql restart

# Monitoring app django instance
- type: compute.v1.instance
  name: authd-django-instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
      networkIP: 10.128.0.61
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - authd-django
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt install python3-pip -y
          sudo mkdir /labs
          cd /labs
          sudo git clone https://github.com/Aguapanela159ap/ISIS2503-Sprints.git
          cd ISIS2503-Sprints
          sudo pip3 install -r requirements.txt
          sudo python3 manage.py makemigrations
          sudo python3 manage.py migrate